# Generated by Django 4.1.6 on 2023-06-08 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Asiento_evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.asiento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('imagen', models.ImageField(upload_to='main/imagenes/')),
                ('fecha_hora', models.DateTimeField()),
                ('disponibles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('mapa', models.ImageField(upload_to='main/imagenes/')),
                ('aforo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('aforo', models.IntegerField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Zona_evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibles', models.IntegerField()),
                ('precio', models.FloatField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.evento')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=9)),
                ('fecha_nac', models.DateField()),
                ('direccion', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.sala'),
        ),
        migrations.CreateModel(
            name='Compra_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('total', models.FloatField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('zona_evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.zona_evento')),
            ],
        ),
        migrations.CreateModel(
            name='Compra_asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento_evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.asiento_evento')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.compra_total')),
            ],
        ),
        migrations.AddField(
            model_name='asiento_evento',
            name='zona_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.zona_evento'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.zona'),
        ),
    ]
